[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["google-auth-library", "googleapis"]

[dev]
  targetPort = 8080

# Redirects para funciones serverless - deben ir primero
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Redirect para SPA - debe ser el último para que React Router maneje las rutas
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para CORS
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET,HEAD,OPTIONS,POST,PUT"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"